### ISSUE TITLE
R studio `git` tab not registering addition of folder to repo

### ISSUE THREAD

**Issue by lucy-schick** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#149] opened 2024-04-07 19:56 UTC
**Issue:**
The R studio `git` tab is not registering the addition of the `inputs_extracted` folder to the `data` folder (see screenshot). Wondering if this is why there was no `inputs_extracted` folder present in the repo when it is needed to build report, see slack message below. 

> Question about the Bulkley 2022 repo: There are tons of calls to add files to data/inputs_extracted but there no inputs_extracted folder in the repo and none of the files are present… getting errors when trying to build. Not sure if this is some workflow I don’t know about yet or if inputs_extracted got removed by accident? I’ve looked back through the PRs and can’t find any deletions or anything. Going to re-create inputs_extracted and run the code that burns to that folder for now so I can build the report.

**Things I've tried:**
- added a `testing` folder and `testing.R` file to see if `git` would register other changes and it did.
- tried removing and re-adding the `inputs_extracted` folder and it still doesn't register in the `git` tab
- checked if it had already been committed and it hasn't.

![Screen Shot 2024-04-07 at 12 55 15 PM](https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/assets/151881303/0f749eed-353c-4806-8f5e-161d74c05128)

**Comment by lucy-schick** [comment] 2024-04-07 20:45
Found the issue, the `extracted_inputs` folder was in `.gitignore`, is there a reason for that?

![Screen Shot 2024-04-07 at 1 44 25 PM](https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/assets/151881303/20ee8ff9-3dbb-47ad-bd35-3ca8e2071415)

**Comment by NewGraphEnvironment** [comment] 2024-04-08 15:06
idea at the time - I think - was that because the data was extracted it could be reproduced so didn't need to be pushed to repo.  not really practical though.  pushed in separate branch and merged with https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/pull/150

**Closed as completed by NewGraphEnvironment** 2024-04-08 15:06 UTC
